package io.github.dev_ritik.cafe;

public class ClientJson {
    private String checkInTime;

    private String checkOutTime;

    // Standard getters & setters generated by your IDE…


    public ClientJson() {
    }

    public ClientJson(String checkInTime, String checkOutTime) {
        this.checkInTime = checkInTime;
        this.checkOutTime = checkOutTime;
    }

    public String getCheckInTime() {
        return checkInTime;
    }

    public void setCheckInTime(String checkInTime) {
        this.checkInTime = checkInTime;
    }

    public String getCheckOutTime() {
        return checkOutTime;
    }

    public void setCheckOutTime(String checkOutTime) {
        this.checkOutTime = checkOutTime;
    }
}